require('stdlib/core')

require('prototypes/adjustment-pad')
require('prototypes/styles')
require('prototypes/sprites')

require('prototypes/picker')
require('prototypes/blueprinter')
require('prototypes/eqkeys')
require('prototypes/tools')
require('prototypes/renamer')
require('prototypes/dollies')
require('prototypes/zapper')
require('prototypes/orphans')
require('prototypes/notes')
require('prototypes/coloredbooks')
require('prototypes/vehicles')
require('prototypes/nakedrails')
