-------------------------------------------------------------------------------
--[[Button Sprites]]--
-------------------------------------------------------------------------------
data:extend{
    {
        type="sprite",
        name="picker-mirror-sprite",
        filename = "__PickerExtended__/graphics/mirror.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
    {
        type="sprite",
        name="picker-upgrade-sprite",
        filename = "__PickerExtended__/graphics/upgrade.png",
        priority = "extra-high",
        width = 32,
        height = 32,
    },
    --[[requests]]--
    {
        type="sprite",
        name="picker-request-bp",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 320,
        y = 0,
    },
    {
        type="sprite",
        name="picker-request-2x",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 384,
        y = 0,
    },
    {
        type="sprite",
        name="picker-request-5x",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 448,
        y = 0,
    },
    {
        type="sprite",
        name="picker-request-10x",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 512,
        y = 0,
    },
    {
        type="sprite",
        name="picker-request-max",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 576,
        y = 0,
    },
    {
        type="sprite",
        name="picker-request-clear",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 256,
        y = 0,
    },
    --[[Filters]]--
    {
        type="sprite",
        name="picker-filters-all",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 0,
        y = 0,
    },
    {
        type="sprite",
        name="picker-filters-down",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 64,
        y = 0,
    },
    {
        type="sprite",
        name="picker-filters-right",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 128,
        y = 0,
    },
    {
        type="sprite",
        name="picker-filters-set-all",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 192,
        y = 0,
    },
    {
        type="sprite",
        name="picker-filters-clear-all",
        filename = "__PickerExtended__/graphics/filterfill.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        x = 256,
        y = 0,
    },
}
